name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download custom Maven
        run: |
          wget http://mirror.example.com/pub/maven/maven-3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
          tar xzf apache-maven-3.6.3-bin.tar.gz
          
      - name: Build with custom Maven
        run: apache-maven-3.6.3/bin/mvn --batch-mode --update-snapshots package